# Generated by Django 4.1.3 on 2022-12-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsersAuthentication', '0002_delete_customusermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
