# Generated by Django 4.1.3 on 2022-12-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuthentication', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestoremodel',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagestoremodel',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
