# Generated by Django 4.1.3 on 2022-12-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuthentication', '0004_imagestoremodel_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageStoreModel',
        ),
    ]
