# Generated by Django 4.1.3 on 2022-11-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MessageHandleEngine', '0002_delete_messagesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=10000000000)),
                ('message', models.CharField(max_length=6000)),
            ],
        ),
    ]
