# Generated by Django 4.1.3 on 2022-11-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageHandleEngine', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessagesModel',
        ),
    ]
