# Generated by Django 4.1.3 on 2022-11-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageHandleEngine', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessagesModel',
        ),
    ]
