# Generated by Django 4.1.3 on 2022-12-09 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageHandleEngine', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 9, 12, 16, 50, 107888), null=True),
        ),
    ]
